apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: public.ecr.aws/b5z4s5t8/cms-repo:db
        name: database
        ports:
        - containerPort: 3306
